[package]
name = "mcu_helper"
version = "0.1.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.3"
cortex-m-rtic = "0.5.5"

[dependencies.stm32l0xx-hal]
version = "0.6"
features = ["rt", "mcu-STM32L031C6Ux"]